version: '3.9'

services:
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  minio_init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      echo 'sleeping for 10 seconds while minio starts...';
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb minio/mybucket;
      /usr/bin/mc anonymous set download minio/mybucket;
      /usr/bin/mc cp --recursive /media/ minio/mybucket/;
      /usr/bin/mc find minio/mybucket --exec '/usr/bin/mc cp --attr Content-Type=application/octet-stream {} {}';
      exit 0;
      "
    volumes:
      - ./data:/media
